image: haskell:8.8.4

stages:
  - test

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"
  STACK_OPTS: "--system-ghc"

comprehension:
  stage: test
  script:
    - stack $STACK_OPTS test :comprehension

mapfilter:
  stage: test
  script:
    - stack $STACK_OPTS test :mapfilter

concatmap:
  stage: test
  script:
    - stack $STACK_OPTS test :concatmap

